### ISSUE TITLE
Title bar

### ISSUE THREAD

**Issue by xmha97** [yasandev/tehro-android#15]
# 📄 Description
Hi, I have installed Tehro from the F-Droid.
In dark mode and light mode, the title bar color is light.
![image](https://user-images.githubusercontent.com/23485114/153777748-e196a363-20c7-406b-9dbb-e8ba6f5df079.png)

# ✔️ Expected UI
![Screenshot_2022-02-14-01-35-52-832_dev yasan metro fdroid](https://user-images.githubusercontent.com/23485114/153777766-04edb69e-7dbd-4f19-a540-af3294d3ced3.jpg)

# ❌ Actual UI
![Screenshot_2022-02-14-01-35-51-832_dev yasan metro fdroid](https://user-images.githubusercontent.com/23485114/153777773-cd8731a9-d3d2-493d-9af3-e11114372820.jpg)

**Comment by yasandev** [comment]
The current title bar color is Tehro's primary theme color which is intended to be used all the time. But still it's a bit too hard + the theme color doesn't mean much when the app is this colorful. I'll take a look into adjusting the theme colors.

**Comment by yasandev** [comment]
Just adjusted the title & status bar colors a bit. I will have to adjust the base theme colors as well but the title bar and status bar part is done and available on [muted-theme](https://github.com/yasandev/tehro-android/tree/muted-theme) branch.
![Screenshot_20220214_024446](https://user-images.githubusercontent.com/41836211/153780003-fb910f6a-6dd3-43ee-9f73-d8291c965862.png)
![Screenshot_20220214_024458](https://user-images.githubusercontent.com/41836211/153780009-335c3758-3d86-4cbc-816b-b05b91973c2d.png)

**Comment by xmha97** [comment]
> Just adjusted the title & status bar colors a bit. I will have to adjust the base theme colors as well but the title bar and status bar part is done and available on [muted-theme](https://github.com/yasandev/tehro-android/tree/muted-theme) branch. ![Screenshot_20220214_024446](https://user-images.githubusercontent.com/41836211/153780003-fb910f6a-6dd3-43ee-9f73-d8291c965862.png) ![Screenshot_20220214_024458](https://user-images.githubusercontent.com/41836211/153780009-335c3758-3d86-4cbc-816b-b05b91973c2d.png)

Thanks, this is exactly what I wanted.

**Comment by yasandev** [comment]
Implemented and merged on #22 and will be available on the next update
