### ISSUE TITLE
Search Support

### ISSUE THREAD

**Issue by xmha97** [yasandev/tehro-android#16]
# 📄 Description
Hi, I need the search feature.
Sometimes I forget which line my station is on.
# ✔️ Expected UI
![image](https://user-images.githubusercontent.com/23485114/153778466-8c114863-3cbd-41c7-99ff-797fc911f126.png)

**Comment by xmha97** [comment]
> Looks like this issue has not been updated in 14 days. Is it still needed?

Yes

**Comment by yasandev** [comment]
Implemented & will be available on the next release.

https://github.com/yasandev/tehro-android/pull/42
