### ISSUE TITLE
Set "social preview" image

### ISSUE THREAD

**Issue by xmha97** [yasandev/tehro-android#17]
Please set "social preview" image:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview
![image](https://user-images.githubusercontent.com/23485114/153779084-8a5ae59e-0b51-4f4a-aa46-972bb37ff732.png)
https://github.com/yasandev/tehro-android/settings

You can use this image:
![image](https://raw.githubusercontent.com/yasandev/tehro-branding/main/PROMO.png)

**Comment by yasandev** [comment]
Just did for all 3 tehro repositories.

**Comment by xmha97** [comment]
> Just did for all 3 Tehro repositories.

I think you did not upload the image to the main repository :(

![image](https://user-images.githubusercontent.com/23485114/153780262-c94913d0-ddb5-4c65-a46d-92260d233c94.png)

**Comment by yasandev** [comment]
I have :/ it might just take some time to update or something. Ill reset it if it doesn't start to work after a few hours.

**Comment by xmha97** [comment]
It's fixed. 👍
![image](https://user-images.githubusercontent.com/23485114/153839893-6ac42e44-0934-4740-b429-da3ccc8ccff8.png)

**Comment by yasandev** [comment]
Great
