### ISSUE TITLE
Use a better icon

### ISSUE THREAD

**Issue by xmha97** [yasandev/tehro-android#18]
Hi YASAN,
The icon is very general and It does not represent the subway (metro).
Please use a better icon like this:

https://user-images.githubusercontent.com/23485114/153926178-02ff3f01-949a-412a-9955-e83086ff2134.svg

![Tehro](https://user-images.githubusercontent.com/23485114/153926178-02ff3f01-949a-412a-9955-e83086ff2134.svg)

**Comment by yasandev** [comment]
Thanks. These types of design suggestions/issues are not welcome as I know what type of design I am aiming for. But you are more than welcome to create your own fork with this icon.
