### ISSUE TITLE
Add language options

### ISSUE THREAD

**Issue by xmha97** [yasandev/tehro-android#26]
سلام
من ترجیح میدم گوشیم انگلیسی باشه اما از این برنامه به صورت فارسی استفاده کنم.
و همین طور درمورد تم، یعنی گوشیم دارک باشه اما از این برنامه به صورت لایت استفاده کنم.
امکان داره به برنامه بخش تنظیمات اضافه کنید که کاربر بتونه انتخاب کنه؟ (مثل تمامی برنامه‌های دیگه)

**Comment by rzasharifi** [comment]
درود. شروع کننده‌ی محترم این درخواست رو بستن ولی من هنوز این مشکلات رو دارم. یعنی میخوام زبان گوشیم انگلیسی باشه و برنامه فارسی که این‌طور نیست.
