### ISSUE TITLE
Nearest stations

### ISSUE THREAD

**Issue by xmha97** [yasandev/tehro-android#36]
![Screenshot_2022-03-03-08-03-35-875_co.fardad.android.metro.jpg](https://user-images.githubusercontent.com/23485114/156497225-4e095c2a-40df-444d-aa56-ad46d9ef3608.jpg)

**Comment by rzasharifi** [comment]
درود، اگر امکانش هست حداقل انتخاب ایستگاه به صورت دستی رو اضافه کنید تا وقتی که همه‌ی ایستگاه ها اضافه بشن. مثلاً من میدونم ایستگاه الف و ب مبدا و مقصد من هست ولی نمی‌دونم توی کدوم ایستگاه‌ها خط‌ها رو میتونم عوض کنم.
