### ISSUE TITLE
Add the Android TV banner

### ISSUE THREAD

**Issue by xmha97** [yasandev/tehro-android#41]
# 📄 Current UI
![image](https://user-images.githubusercontent.com/23485114/159478391-921a3cc6-3310-4a5d-b137-a046d519682e.png)

# ✔️ Expected UI
![image](https://user-images.githubusercontent.com/23485114/159478690-5fa687b0-7bae-43d2-b80c-1894ba5724e1.png)

**Comment by xmha97** [comment]
سلام، عذرمی‌خوام میشه این فیچر رو تو اولویت قرار بدید؟
شاید بگید هیچ کسی اینو رو تلوزیونش نصب نمی‌کنه که کاملا هم درسته، اما برا من که قراره رو تلوزیون محل کارم نصب کنم، کاربردیه.
انجام دادنش هم کار سختی نیست، باید چند خط کد تو فایل مانیفست و یه بنر (آیکون) برا لانچر اندروید تی‌وی اضافه کنید.

شاید این لینک کمک کننده باشد:
https://stackoverflow.com/a/56232518
ممنون

**Comment by yasandev** [comment]
#45 adds TV banner support

**Comment by xmha97** [comment]
Thanks 😘
